services:
  hikstatus:
    build: .
    container_name: hikstatus
    restart: always
    volumes:
      - ./data:/app/data
      - ./camera_names.csv:/app/camera_names.csv
    environment:
      - TZ=Asia/Tehran
      - PYTHONUNBUFFERED=1      
    networks:
      - proxy_net

networks:
  proxy_net:
    name: proxy_net
    external: true      